# Generated by Django 5.0.6 on 2024-07-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_parent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
