# Generated by Django 5.0.6 on 2024-06-30 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVNPAYDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('order_desc', models.CharField(max_length=100)),
                ('vnp_TransactionNo', models.CharField(max_length=20)),
                ('vnp_ResponseCode', models.CharField(max_length=20)),
                ('vnp_PayDate', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerce.order')),
            ],
        ),
    ]
