# Generated by Django 5.0.6 on 2024-06-26 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_alter_productdetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopconfirmation',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_confirmationstatus', to='eCommerce.shopconfirmationstatus'),
        ),
        migrations.AlterField(
            model_name='shopconfirmation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopconfirmation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopconfirmationstatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
