# Generated by Django 5.0.6 on 2024-07-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_rename_rating_product_product_rating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRating',
            new_name='ProductReview',
        ),
        migrations.RenameModel(
            old_name='ShopRating',
            new_name='ShopReview',
        ),
    ]
