# Generated by Django 5.0.6 on 2024-06-26 07:50

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0003_alter_shop_user_alter_shopconfirmation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfirmation',
            name='shop_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopconfirmation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_confirmationstatus', to='eCommerce.shopconfirmationstatus'),
        ),
        migrations.AlterField(
            model_name='shopconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopconfirmation', to=settings.AUTH_USER_MODEL),
        ),
    ]
