# Generated by Django 5.0.6 on 2024-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0003_rename_productrating_productreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_rating',
            field=models.FloatField(default=0),
        ),
    ]
