# Generated by Django 5.0.6 on 2024-06-25 02:40

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfirmationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('following', models.IntegerField(default=0)),
                ('followed', models.IntegerField(default=0)),
                ('rated', models.FloatField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('citizen_identification_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('shop_name', models.CharField(max_length=100, unique=True)),
                ('shop_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('shop_description', ckeditor.fields.RichTextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eCommerce.shopconfirmationstatus')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
